### ISSUE TITLE
No image found in pdfs

### ISSUE THREAD

**Issue by VictorZuanazzi** [Mini-Conf/image-extraction#1]
I have not been successful in extracting images from pdfs. 

```
python run.py pdfs/ pics/
mkdir: cannot create directory ‘dataset’: File exists
mkdir: cannot create directory ‘out’: File exists
rm: cannot remove 'dataset/*': No such file or directory
rm: cannot remove 'out/*': No such file or directory
No pic found for pdfs/1111.7295.pdf
rm: cannot remove 'out/*': No such file or directory
No pic found for pdfs/1111.5867.pdf
rm: cannot remove 'out/*': No such file or directory
No pic found for pdfs/1111.5948.pdf
rm: cannot remove 'out/*': No such file or directory
No pic found for pdfs/1111.5479.pdf
```

The pdfs are saved in the folder `pdfs`.
The specific files in this demo are (all have images):

- [1111.7295](https://arxiv.org/pdf/1111.7295.pdf)
- [1111.5867](https://arxiv.org/pdf/1111.5867.pdf)
- [1111.5948](https://arxiv.org/pdf/1111.5948.pdf)
- [1111.5479](https://arxiv.org/pdf/1111.5479.pdf)

However, I tried with 150+ pdfs and did not get any image.

Any suggestions of what could be going wrong?

**Comment by srush** [comment]
Okay, I think I found the issue. 

Try with new `--max_page 50` 

Here is an example on your data: 

https://colab.research.google.com/drive/1kRYiYSoGu2CB0zZEwR3616lmxd51y9-N?usp=sharing

**Comment by srush** [comment]
![image](https://user-images.githubusercontent.com/35882/92161361-88c04700-edfe-11ea-9c52-b55ea4a2f039.png)

**Comment by VictorZuanazzi** [comment]
Still no success. I am suspecting something is going wrong when calling of `infer_simple.py`. It seems it throws an error and does not finish its execution. 
I have reinstalled all dependencies in a new environment. But no success yet. Any tips?

*Update:* The file tmp.err shows the following error

```
ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "infer_simple.py", line 29, in <module>
    import cv2  # NOQA (Must import before importing caffe2 due to bug in cv2)
ImportError: numpy.core.multiarray failed to import
```

Which numpy version are you using? 

```
Python 3.6.10 |Anaconda, Inc.| (default, May  8 2020, 02:54:21) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.__version__
'1.19.1'
```

**Comment by srush** [comment]
1.18.5

Maybe cv2 is hitting an older version on you system?

**Comment by VictorZuanazzi** [comment]
It seems cv2 is the problem indeed. My version is 3.3 and the one from collab is 4.1.
`conda install -c conda-forge opencv` did not solve the issue. I will bring an update once I have a working solution (or find a new issue!)

**Comment by AnirudhDagar** [comment]
Hi, @srush The collab notebook you shared doesn't work with some pdfs even when there are images.
One example is this -> https://openreview.net/pdf?id=B1e9Y2NYvS

Are you able to extract the images from the provided pdf? The ICLR conference virtual website shows the [image thumbnail](https://iclr.cc/virtual/papers.html?filter=authors&search=Hanshu+YAN) for the same paper, but for me, it is not working somehow.

Can you please help?

**Comment by srush** [comment]
The model is very bad at wrapfig like in that pdf. Apparently that never occurred in the underlying dataset.

**Comment by AnirudhDagar** [comment]
I see that makes sense. But I don't understand how the same image was extracted for the same paper in the ICLR images repo [here](https://github.com/ICLR/iclr-images/blob/master/B1e9Y2NYvS.png)? Was that added manually?

I ran this image-extraction model for all the 687 accepted ICLR 2020 papers but could not reproduce all the results as in the [iclr-images](https://github.com/ICLR/iclr-images) repo. I was able to extract 543 images from the 687 papers. Assuming that there can be a few(10-20) papers with no images, 144 is still a big number for the papers left. Did you face the same issue while extracting these for ICLR 2020 virtual website?

Thanks in advance.

**Comment by srush** [comment]
Hmm, it's possible we ran it for ICLR with a different threshold cutoff. You could change this line and try again. https://github.com/Mini-Conf/image-extraction/blob/master/infer_simple.py#L186

**Comment by AnirudhDagar** [comment]
Thanks a lot, @srush. It works perfectly now. ❤️ 
I had to install a few more dependencies for running it on a GPU instance (not collab, which already has a lot of requirements like caffe2 and open-cv pre-installed). I'm leaving a link to my [fork](https://github.com/anirudhdagar/image-extraction/) just in case someone stumbles upon this issue later.

Also one non-DL alternative to image extraction is [pdffigures2](https://github.com/allenai/pdffigures2) by allenai. Maybe useful to others.

Thanks again!

**Comment by srush** [comment]
Great to hear. Thanks for the links.
